language: ruby
rvm: 2.3.0
services:
  - postgresql

env:
  test:
    - OBKWEB_DB_HOST=localhost
    - OBKWEB_DB_PORT=5432
    - OBKWEB_DB_USER=postgres

bundler_args: --without production

before_script:
  - psql -c 'create database obkweb_test;' -U postgres
  - bundle exec rake db:migrate RAILS_ENV=test

cache: bundler

script:
  - bundle exec rspec
  - bundle exec rubocop