language: ruby
rvm: 2.3.0
services:
  - postgresql

addons:
  postgresql: "9.4"

env:
  test:
    - OBKWEB_DB_HOST=localhost
    - OBKWEB_DB_PORT=5432
    - OBKWEB_DB_USER=postgres

bundler_args: --without production

before_script:
  - psql -c 'create database obkweb_test;' -U postgres
  - bundle exec rake db:migrate RAILS_ENV=test

cache: bundler

notifications:
  slack: socialcolab:JgDTv1GQZ5jsyTk1GcrV4TFw

script:
  - bundle exec rspec
